buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Asegúrate de usar una versión de AGP 8.0.0 o superior compatible con Gradle 8.1.1
        classpath 'com.android.tools.build:gradle:8.1.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
